[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.1"
dependencies = [
    "pydantic-settings>=2.7.1",
    "torch>=2.5.1",
]

[tool.ruff.format]
quote-style = "single"
