[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.1"
dependencies = [
    "pydantic>=2.10.5",
    "pydantic-ai>=0.0.19",
    "pydantic-settings>=2.7.1",
]

[tool.ruff.format]
quote-style = "single"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "mypy>=1.14.1",
]
